// <auto-generated>
// Code generated by LUISGen .\ShoppingBot.json -cs Luis.ShoppingBot -o .
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.Luis;

namespace Chat.Core.Entities
{
    public partial class ShoppingBot: IRecognizerConvert
    {
        [JsonProperty("text")]
        public string Text;

        [JsonProperty("alteredText")]
        public string AlteredText;

        public enum Intent {
            AddElementToList, 
            CreateEvent, 
            CreateList, 
            DeleteList, 
            FindRecipes, 
            GetAllLists, 
            None, 
            RemoveElementFromList, 
            SelectRecipeResult, 
            ShowList
        };
        [JsonProperty("intents")]
        public Dictionary<Intent, IntentScore> Intents;

        public class _Entities
        {
            // Simple entities
            public string[] Activity;

            public string[] ListName;

            public string[] ProductName;

            public string[] SelectedRecipe;

            // Built-in entities
            public DateTimeSpec[] datetime;

            // Instance
            public class _Instance
            {
                public InstanceData[] Activity;
                public InstanceData[] ListName;
                public InstanceData[] ProductName;
                public InstanceData[] SelectedRecipe;
                public InstanceData[] datetime;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        [JsonProperty("entities")]
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<ShoppingBot>(JsonConvert.SerializeObject(result, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore }));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score.Value;
                }
            }
            return (maxIntent, max);
        }
    }
}
